name: hashendo
favicon: null
layout_spectrum: 0.49803185486234725
typography_spectrum: 0.5206054963637143
title: Your source for all things mary jane
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.543571645161137
  lightness: 0.5993172388989478
  saturation: 0.6042607212439179
  rhythmicContrast: 0.7571708364412189
purpose: []
